package it.sitodskij.myblueprint.util.enums;

public enum ExcelInputPrestazione_Enum {

	IDXRIGA_NOMEFONDO(1),
	IDXRIGA_CF_FONDO(3),
	IDXRIGA_ANNO_FONDO(5),
	IDXRIGA_STARTING_ROWDATA(9),
	
	IDXCOL_NOMEFONDO(1),
	IDXCOL_CF_FONDO(1),
	IDXCOL_ANNO_FONDO(1),
	IDXCOL_NATURA_PRESTAZ(1),
	IDXCOL_NOME_MACROAMBITO(2),
	IDXCOL_LIVELLO_ASSISTENZIALE(3),
	IDXCOL_TIPOLOGIA(4),
	IDXCOL_INSERITA_PERCORSO_ASSISTENZ(5),
	IDXCOL_DESCRIZIONE_PERCORSI(6),
	IDXCOL_NUMERO_PRESTAZIONI_TICKET(7),
	IDXCOL_VALORE_COMPLESSIVO_TICKET(8),
	IDXCOL_NUMERO_PRESTAZIONI_INTERO(9),
	IDXCOL_VALORE_COMPLESSIVO_INTERO(10),
	IDXCOL_QTA_TOT_EROGATE(11),
	IDXCOL_VALORE_COMPLESSIVO(12),
	IDXCOL_PRESTAZ_ANNUE_GARANT(13);
	
	public int idx;
	private ExcelInputPrestazione_Enum(int idx) {this.idx = idx;}
}
